### ISSUE TITLE
Get video and imagery of the Field Test on the field test wiki

### ISSUE THREAD

**Issue by qjhart** [CSTARS/ahb-field-work#3]
Let's push some of our video into youtube, and put in links into the documentation.  Also, let's jupload some of the photos as well.

**Comment by hitchpy** [comment]
http://youtu.be/DgksQ1W3FEY
http://youtu.be/vHXg7he8eYI
http://imgur.com/a/H892o

**Comment by qjhart** [comment]
Looks great! But you need to update the Github wiki as well, so those can
be found.

quinn

On Thu, Nov 13, 2014 at 2:14 PM, yu pei notifications@github.com wrote:

> http://youtu.be/DgksQ1W3FEY
> http://youtu.be/vHXg7he8eYI
> http://imgur.com/a/H892o
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CSTARS/ahb-field-work/issues/3#issuecomment-62976487.

## 

Quinn Hart -- Land, Air, and Water Resources -- University of California
Davis, CA 95616-8628

**Comment by hitchpy** [comment]
alright, will do
